# ~/environment/sam-app/buildspec.yml

version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      # Install packages or any pre-reqs in this phase.
      - npm install
      - npm audit fix
  
  # pre_build:
  #   commands:
  #     # Run tests, lint scripts or any other pre-build checks.
  #     - npm run test

  build:
    commands:
      # Use Build phase to build your artifacts (compile, etc.)
      - npm run-script build

artifacts:
  # discard-paths: yes
  files:
    - '**/*'
  base-directory: build
